worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    sendfile        on;
    keepalive_timeout  65;

    # Backend API Gateway
    upstream api_gateway {
        server api-gateway:8080;
    }

    # Frontend Application
    upstream customer_portal {
        server customer-portal:3000;
    }

    server {
        listen 80;
        server_name localhost;

        # Route API requests to the Spring Cloud Gateway
        location /api/ {
            include proxy_params;
            proxy_pass http://api_gateway/;
        }

        # Route all other requests to the Next.js Frontend
        location / {
            include proxy_params;
            proxy_pass http://customer_portal;
        }
    }
}
