apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
