apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Release.Name }}-mongo
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mongo.storage }}
