apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmart-backend
  namespace: cloudmart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudmart-backend
  template:
    metadata:
      labels:
        app: cloudmart-backend
    spec:
      containers:
        - name: backend
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/cloudmart-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
            - name: MONGO_URI
              value: mongodb://cloudmart-mongo:27017/cloudmart
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
