apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cravedrop-dev
resources: [../../base, namespace.yaml]
replicas:
  - {name: backend, count: 1}
  - {name: frontend, count: 1}
configMapGenerator:
  - name: backend-config
    behavior: merge
    literals: [NODE_ENV=development, TRUST_PROXY_HOPS=1, "ALLOWED_ORIGINS=http://localhost:8080"]
patches:
  - target: {kind: PodDisruptionBudget}
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 0
